[package]
name = "cyclos-core"
version = "0.1.0"
description = "Core program for pool management"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "cyclos_core"
doctest = false

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.18.0"
anchor-spl = "0.18.0"
ux = "0.1.3"
bitmaps = "3.1.0"
# non_fungible_position_manager = { path = "../non_fungible_position_manager", features = ["cpi"] }
